# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from test import *

class confirmation(object):
    def setupUi(self, confirm_window):
        confirm_window.setObjectName("confirm_window")
        confirm_window.resize(1024, 600)
        confirm_window.setMinimumSize(QtCore.QSize(1024, 600))
        confirm_window.setMaximumSize(QtCore.QSize(1024, 600))
        self.centralwidget = QtWidgets.QWidget(confirm_window)
        self.centralwidget.setObjectName("centralwidget")
        self.TITLE = QtWidgets.QLabel(self.centralwidget)
        self.TITLE.setGeometry(QtCore.QRect(0, 40, 1021, 91))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.TITLE.setFont(font)
        self.TITLE.setAlignment(QtCore.Qt.AlignCenter)
        self.TITLE.setObjectName("TITLE")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 250, 291, 161))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(560, 250, 271, 161))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        confirm_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(confirm_window)
        self.statusbar.setObjectName("statusbar")
        confirm_window.setStatusBar(self.statusbar)

        self.retranslateUi(confirm_window)
        QtCore.QMetaObject.connectSlotsByName(confirm_window)

    def retranslateUi(self, confirm_window):
        _translate = QtCore.QCoreApplication.translate
        confirm_window.setWindowTitle(_translate("confirm_window", "confirm_window"))
        self.TITLE.setText(_translate("confirm_window", "End procedure?"))
        self.pushButton_2.setText(_translate("confirm_window", "No"))
        self.pushButton_3.setText(_translate("confirm_window", "Yes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    confirm_window = QtWidgets.QMainWindow()
    ui = confirmation()
    ui.setupUi(confirm_window)
    confirm_window.show()
    sys.exit(app.exec_())
