# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'request_nurse.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from scan_qr_code import *

class request_nurse(object):
    
    def close_window(self):
        self.window_qr_program = QtWidgets.QMainWindow()
        self.ui = qr_scanner_window()
        self.ui.setupUi(self.window_qr_program)
        self.window_qr_program.show()
        
        
    def setupUi(self, request_nurse_window):
        request_nurse_window.setObjectName("request_nurse_window")
        request_nurse_window.resize(1024, 600)
        request_nurse_window.setMinimumSize(QtCore.QSize(1024, 600))
        request_nurse_window.setMaximumSize(QtCore.QSize(1024, 600))
        self.centralwidget = QtWidgets.QWidget(request_nurse_window)
        self.centralwidget.setObjectName("centralwidget")
        self.TITLE = QtWidgets.QLabel(self.centralwidget)
        self.TITLE.setGeometry(QtCore.QRect(0, 50, 1021, 311))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.TITLE.setFont(font)
        self.TITLE.setAlignment(QtCore.Qt.AlignCenter)
        self.TITLE.setObjectName("TITLE")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked = self.close_window)
        self.pushButton.setGeometry(QtCore.QRect(330, 420, 361, 131))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        request_nurse_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(request_nurse_window)
        self.statusbar.setObjectName("statusbar")
        request_nurse_window.setStatusBar(self.statusbar)

        self.retranslateUi(request_nurse_window)
        QtCore.QMetaObject.connectSlotsByName(request_nurse_window)

    def retranslateUi(self, request_nurse_window):
        _translate = QtCore.QCoreApplication.translate
        request_nurse_window.setWindowTitle(_translate("request_nurse_window", "request_nurse_window"))
        self.TITLE.setText(_translate("request_nurse_window", "Please wait for a \n"
" Clinic Staff to arrive."))
        self.pushButton.setText(_translate("request_nurse_window", "End Procedure"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    request_nurse_window = QtWidgets.QMainWindow()
    ui = request_nurse()
    ui.setupUi(request_nurse_window)
    request_nurse_window.show()
    sys.exit(app.exec_())
