# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_injury_type.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from search_injury import *
from step_1 import *

class select_injury_type(object):
    
    def open_search_injury(self):
        self.window_search_injury = QtWidgets.QMainWindow()
        self.ui = search_injury()
        self.ui.setupUi(self.window_search_injury)
        self.window_search_injury.show()
        
    def wound_injury(self):
        self.window_step_1 = QtWidgets.QMainWindow()
        self.ui = step_1()
        self.ui.setupUi(self.window_step_1)
        self.window_step_1.show()
        
    def setupUi(self, injury_type_window):
        injury_type_window.setObjectName("injury_type_window")
        injury_type_window.resize(1024, 600)
        injury_type_window.setMinimumSize(QtCore.QSize(1024, 600))
        injury_type_window.setMaximumSize(QtCore.QSize(1024, 600))
        self.centralwidget = QtWidgets.QWidget(injury_type_window)
        self.centralwidget.setObjectName("centralwidget")
        self.TITLE = QtWidgets.QLabel(self.centralwidget)
        self.TITLE.setGeometry(QtCore.QRect(0, 10, 1021, 91))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.TITLE.setFont(font)
        self.TITLE.setAlignment(QtCore.Qt.AlignCenter)
        self.TITLE.setObjectName("TITLE")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget, clicked = self.wound_injury)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 120, 311, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 120, 311, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 350, 311, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(700, 120, 301, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget, clicked = self.open_search_injury)
        self.pushButton_6.setGeometry(QtCore.QRect(360, 350, 311, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(700, 350, 311, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        injury_type_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(injury_type_window)
        QtCore.QMetaObject.connectSlotsByName(injury_type_window)

    def retranslateUi(self, injury_type_window):
        _translate = QtCore.QCoreApplication.translate
        injury_type_window.setWindowTitle(_translate("injury_type_window", "injury_type_window"))
        self.TITLE.setText(_translate("injury_type_window", "Select type of Injury"))
        self.pushButton_2.setText(_translate("injury_type_window", "WOUND"))
        self.pushButton_3.setText(_translate("injury_type_window", "CUT"))
        self.pushButton_4.setText(_translate("injury_type_window", "BURN"))
        self.pushButton_5.setText(_translate("injury_type_window", "PUNCTURE"))
        self.pushButton_6.setText(_translate("injury_type_window", "OTHERS"))
        self.pushButton_7.setText(_translate("injury_type_window", "GO BACK TO \n"
"BODY PARTS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    injury_type_window = QtWidgets.QMainWindow()
    ui = select_injury_type()
    ui.setupUi(injury_type_window)
    injury_type_window.show()
    sys.exit(app.exec_())
