# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_body_part.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from select_injury_type import *

class select_body_part(object):
    
    def open_select_injury_type(self):
        self.window_injury_type = QtWidgets.QMainWindow()
        self.ui = select_injury_type()
        self.ui.setupUi(self.window_injury_type)
        #body_parts_window.hide()
        self.window_injury_type.show()
        
    def setupUi(self, body_parts_window):
        body_parts_window.setObjectName("body_parts_window")
        body_parts_window.resize(1024, 600)
        body_parts_window.setMinimumSize(QtCore.QSize(1024, 600))
        body_parts_window.setMaximumSize(QtCore.QSize(1024, 600))
        self.centralwidget = QtWidgets.QWidget(body_parts_window)
        self.centralwidget.setObjectName("centralwidget")
        self.TITLE = QtWidgets.QLabel(self.centralwidget)
        self.TITLE.setGeometry(QtCore.QRect(0, 0, 1021, 91))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(24)
        self.TITLE.setFont(font)
        self.TITLE.setAlignment(QtCore.Qt.AlignCenter)
        self.TITLE.setObjectName("TITLE")
        self.body_part = QtWidgets.QLabel(self.centralwidget)
        self.body_part.setGeometry(QtCore.QRect(10, 60, 1001, 521))
        self.body_part.setText("")
        self.body_part.setTextFormat(QtCore.Qt.PlainText)
        self.body_part.setPixmap(QtGui.QPixmap("body_part.png"))
        self.body_part.setObjectName("body_part")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked = self.open_select_injury_type)
        self.pushButton.setGeometry(QtCore.QRect(761, 308, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(36)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        body_parts_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(body_parts_window)
        QtCore.QMetaObject.connectSlotsByName(body_parts_window)

    def retranslateUi(self, body_parts_window):
        
        _translate = QtCore.QCoreApplication.translate
        body_parts_window.setWindowTitle(_translate("body_parts_window", "BODY PARTS SELECTION"))
        self.TITLE.setText(_translate("body_parts_window", "Select body Part"))
        self.pushButton.setText(_translate("body_parts_window", "HAND"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    body_parts_window = QtWidgets.QMainWindow()
    ui = select_body_part()
    ui.setupUi(body_parts_window)
    body_parts_window.show()
    sys.exit(app.exec_())
