# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'step_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from confirmation import *

class step_3(object):
    
    def open_confirmation(self):
        self.window_confirmation = QtWidgets.QMainWindow()
        self.ui = confirmation()
        self.ui.setupUi(self.window_confirmation)
        self.window_confirmation.show()
        
    def setupUi(self, step3_window):
        step3_window.setObjectName("step3_window")
        step3_window.resize(1024, 600)
        step3_window.setMinimumSize(QtCore.QSize(1024, 600))
        step3_window.setMaximumSize(QtCore.QSize(1024, 600))
        self.centralwidget = QtWidgets.QWidget(step3_window)
        self.centralwidget.setObjectName("centralwidget")
        self.TITLE = QtWidgets.QLabel(self.centralwidget)
        self.TITLE.setGeometry(QtCore.QRect(0, 0, 1021, 71))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(24)
        self.TITLE.setFont(font)
        self.TITLE.setAlignment(QtCore.Qt.AlignCenter)
        self.TITLE.setObjectName("TITLE")
        self.TITLE_2 = QtWidgets.QLabel(self.centralwidget)
        self.TITLE_2.setGeometry(QtCore.QRect(310, 70, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.TITLE_2.setFont(font)
        self.TITLE_2.setAlignment(QtCore.Qt.AlignCenter)
        self.TITLE_2.setObjectName("TITLE_2")
        self.TITLE_3 = QtWidgets.QLabel(self.centralwidget)
        self.TITLE_3.setGeometry(QtCore.QRect(410, 130, 201, 141))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.TITLE_3.setFont(font)
        self.TITLE_3.setText("")
        self.TITLE_3.setPixmap(QtGui.QPixmap("3rd step bandagign a wound.jpg"))
        self.TITLE_3.setAlignment(QtCore.Qt.AlignCenter)
        self.TITLE_3.setObjectName("TITLE_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 290, 761, 151))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked = self.open_confirmation)
        self.pushButton.setGeometry(QtCore.QRect(790, 470, 221, 111))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 470, 221, 111))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        step3_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(step3_window)
        QtCore.QMetaObject.connectSlotsByName(step3_window)

    def retranslateUi(self, step3_window):
        _translate = QtCore.QCoreApplication.translate
        step3_window.setWindowTitle(_translate("step3_window", "step3_window"))
        self.TITLE.setText(_translate("step3_window", "Bandaging a Wound"))
        self.TITLE_2.setText(_translate("step3_window", "Step 3: Secure the bandage"))
        self.label.setText(_translate("step3_window", " A) Tie or tape the bandage in place.\n"
"\n"
" B) Don\'t secure the bandage so tight that fingers or toes become pale or blue."))
        self.pushButton.setText(_translate("step3_window", "Finish Step"))
        self.pushButton_3.setText(_translate("step3_window", "Go back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    step3_window = QtWidgets.QMainWindow()
    ui = step_3()
    ui.setupUi(step3_window)
    step3_window.show()
    sys.exit(app.exec_())
