# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_injury.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from request_nurse import *

class search_injury(object):
    
    def nurse_request(self):
        self.request_nurse_window = QtWidgets.QMainWindow()
        self.ui = request_nurse()
        self.ui.setupUi(self.request_nurse_window)
        self.request_nurse_window.show()
        
    def setupUi(self, search_injur_window):
        search_injur_window.setObjectName("search_injur_window")
        search_injur_window.resize(1024, 600)
        search_injur_window.setMinimumSize(QtCore.QSize(1024, 600))
        search_injur_window.setMaximumSize(QtCore.QSize(1024, 600))
        self.centralwidget = QtWidgets.QWidget(search_injur_window)
        self.centralwidget.setObjectName("centralwidget")
        self.TITLE = QtWidgets.QLabel(self.centralwidget)
        self.TITLE.setGeometry(QtCore.QRect(0, 0, 1021, 91))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.TITLE.setFont(font)
        self.TITLE.setAlignment(QtCore.Qt.AlignCenter)
        self.TITLE.setObjectName("TITLE")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 110, 801, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked = self.nurse_request)
        self.pushButton.setGeometry(QtCore.QRect(820, 110, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 340, 1071, 271))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("1024x222 keyboard pi.png"))
        self.label.setObjectName("label")
        search_injur_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(search_injur_window)
        self.statusbar.setObjectName("statusbar")
        search_injur_window.setStatusBar(self.statusbar)

        self.retranslateUi(search_injur_window)
        QtCore.QMetaObject.connectSlotsByName(search_injur_window)

    def retranslateUi(self, search_injur_window):
        _translate = QtCore.QCoreApplication.translate
        search_injur_window.setWindowTitle(_translate("search_injur_window", "search_injur_window"))
        self.TITLE.setText(_translate("search_injur_window", "Enter the type of Injury"))
        self.pushButton.setText(_translate("search_injur_window", "Enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    search_injur_window = QtWidgets.QMainWindow()
    ui = search_injury()
    ui.setupUi(search_injur_window)
    search_injur_window.show()
    sys.exit(app.exec_())
