# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'debug_window_6.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_whitelist_error(object):
    def setupUi(self, whitelist_error):
        self.whitelist_window = whitelist_error
        whitelist_error.setObjectName("whitelist_error")
        whitelist_error.resize(1024, 600)
        whitelist_error.setMinimumSize(QtCore.QSize(1024, 600))
        whitelist_error.setMaximumSize(QtCore.QSize(1024, 600))
        self.centralwidget = QtWidgets.QWidget(whitelist_error)
        self.centralwidget.setObjectName("centralwidget")
        self.confirm_button = QtWidgets.QPushButton(self.centralwidget, clicked = self.confirm_window)
        self.confirm_button.setGeometry(QtCore.QRect(355, 360, 311, 141))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.confirm_button.setFont(font)
        self.confirm_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirm_button.setStyleSheet("QPushButton:hover:!pressed\n"
                                    "{\n"
                                    "  background-color: rgb(195,30,60);\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton\n"
                                    "{\n"
                                    "  background-color: white;\n"
                                    "color: black;\n"
                                    "border-style: outset;\n"
                                    "border-width: 3px;\n"
                                    "border-radius:10px;\n"
                                    "border-color: black;\n"
                                    "}\n"
                                    "")
        self.confirm_button.setObjectName("confirm_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 1001, 351))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        whitelist_error.setCentralWidget(self.centralwidget)

        self.retranslateUi(whitelist_error)
        QtCore.QMetaObject.connectSlotsByName(whitelist_error)
        
    def confirm_window(self):
        self.whitelist_window.close()

    def retranslateUi(self, whitelist_error):
        _translate = QtCore.QCoreApplication.translate
        whitelist_error.setWindowTitle(_translate("whitelist_error", "Interactive First Aid Cabinet"))
        self.confirm_button.setText(_translate("whitelist_error", "Confirm"))
        self.label.setText(_translate("whitelist_error", "<html><head/><body><p align=\"center\"><span style=\" font-size:72pt; color:#ff0000;\">ERROR</span><span style=\" font-size:72pt;\">, QR <br/>CODE IS<br/>INVALID.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    whitelist_error = QtWidgets.QMainWindow()
    ui = Ui_whitelist_error()
    ui.setupUi(whitelist_error)
    whitelist_error.show()
    sys.exit(app.exec_())