# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patient_gender.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gender_patient_window(object):
    def setupUi(self, gender_patient_window):
        gender_patient_window.setObjectName("gender_patient_window")
        gender_patient_window.resize(1024, 600)
        gender_patient_window.setMinimumSize(QtCore.QSize(1024, 600))
        gender_patient_window.setMaximumSize(QtCore.QSize(1024, 600))
        self.centralwidget = QtWidgets.QWidget(gender_patient_window)
        self.centralwidget.setObjectName("centralwidget")
        self.TITLE = QtWidgets.QLabel(self.centralwidget)
        self.TITLE.setGeometry(QtCore.QRect(0, 40, 1021, 91))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.TITLE.setFont(font)
        self.TITLE.setAlignment(QtCore.Qt.AlignCenter)
        self.TITLE.setObjectName("TITLE")
        self.male_button = QtWidgets.QPushButton(self.centralwidget)
        self.male_button.setGeometry(QtCore.QRect(30, 230, 291, 201))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.male_button.setFont(font)
        self.male_button.setObjectName("male_button")
        self.female_button = QtWidgets.QPushButton(self.centralwidget)
        self.female_button.setGeometry(QtCore.QRect(365, 230, 291, 201))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.female_button.setFont(font)
        self.female_button.setObjectName("female_button")
        self.not_say_button = QtWidgets.QPushButton(self.centralwidget)
        self.not_say_button.setGeometry(QtCore.QRect(700, 230, 291, 201))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.not_say_button.setFont(font)
        self.not_say_button.setObjectName("not_say_button")
        gender_patient_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(gender_patient_window)
        self.statusbar.setObjectName("statusbar")
        gender_patient_window.setStatusBar(self.statusbar)

        self.retranslateUi(gender_patient_window)
        QtCore.QMetaObject.connectSlotsByName(gender_patient_window)

    def retranslateUi(self, gender_patient_window):
        _translate = QtCore.QCoreApplication.translate
        gender_patient_window.setWindowTitle(_translate("gender_patient_window", "Confirmation Procedure"))
        self.TITLE.setText(_translate("gender_patient_window", "Gender of Patient"))
        self.male_button.setText(_translate("gender_patient_window", "MALE"))
        self.female_button.setText(_translate("gender_patient_window", "FEMALE"))
        self.not_say_button.setText(_translate("gender_patient_window", "PREFER NOT \n"
" TO SAY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gender_patient_window = QtWidgets.QMainWindow()
    ui = Ui_gender_patient_window()
    ui.setupUi(gender_patient_window)
    gender_patient_window.show()
    sys.exit(app.exec_())
