from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_step_1_procedure(object):
    def setupUi(self, step_1_procedure):
        step_1_procedure.setObjectName("step_1_procedure")
        step_1_procedure.resize(1024, 600)
        step_1_procedure.setMinimumSize(QtCore.QSize(1024, 600))
        step_1_procedure.setMaximumSize(QtCore.QSize(1024, 600))
        self.centralwidget = QtWidgets.QWidget(step_1_procedure)
        self.centralwidget.setObjectName("centralwidget")
        self.TITLE = QtWidgets.QLabel(self.centralwidget)
        self.TITLE.setGeometry(QtCore.QRect(0, 0, 1021, 71))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(24)
        self.TITLE.setFont(font)
        self.TITLE.setAlignment(QtCore.Qt.AlignCenter)
        self.TITLE.setObjectName("TITLE")
        self.TITLE_2 = QtWidgets.QLabel(self.centralwidget)
        self.TITLE_2.setGeometry(QtCore.QRect(330, 60, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.TITLE_2.setFont(font)
        self.TITLE_2.setAlignment(QtCore.Qt.AlignCenter)
        self.TITLE_2.setObjectName("TITLE_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 350, 981, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gif_player_label = QtWidgets.QLabel(self.centralwidget)
        self.gif_player_label.setGeometry(QtCore.QRect(330, 100, 360, 240))
        self.gif_player_label.setMinimumSize(QtCore.QSize(360, 240))
        self.gif_player_label.setMaximumSize(QtCore.QSize(360, 240))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.gif_player_label.setFont(font)
        self.gif_player_label.setLineWidth(1)
        self.gif_player_label.setText("")
        self.gif_player_label.setPixmap(QtGui.QPixmap("../1st step bandagign a wound.jpg"))
        self.gif_player_label.setAlignment(QtCore.Qt.AlignCenter)
        self.gif_player_label.setObjectName("gif_player_label")
        self.next_step_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_step_button.setGeometry(QtCore.QRect(760, 480, 251, 111))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.next_step_button.setFont(font)
        self.next_step_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_step_button.setObjectName("next_step_button")
        self.go_back_injury_type = QtWidgets.QPushButton(self.centralwidget)
        self.go_back_injury_type.setGeometry(QtCore.QRect(10, 470, 251, 121))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.go_back_injury_type.setFont(font)
        self.go_back_injury_type.setObjectName("go_back_injury_type")
        step_1_procedure.setCentralWidget(self.centralwidget)

        self.retranslateUi(step_1_procedure)
        QtCore.QMetaObject.connectSlotsByName(step_1_procedure)

    def retranslateUi(self, step_1_procedure):
        _translate = QtCore.QCoreApplication.translate
        step_1_procedure.setWindowTitle(_translate("step_1_procedure", "Step 1 Procedure"))
        self.TITLE.setText(_translate("step_1_procedure", "Bandaging a Wound"))
        self.TITLE_2.setText(_translate("step_1_procedure", "Step 1: Clean the Wound"))
        self.label.setText(_translate("step_1_procedure", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">A) Put on gloves or use other protection to avoid contact with the victim\'s blood</span></p></body></html>"))
        self.next_step_button.setText(_translate("step_1_procedure", "NEXT STEP"))
        self.go_back_injury_type.setText(_translate("step_1_procedure", "GO BACK TO \n"
                                                    " INJURY TYPE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    step_1_procedure = QtWidgets.QMainWindow()
    ui = Ui_step_1_procedure()
    ui.setupUi(step_1_procedure)
    step_1_procedure.show()
    sys.exit(app.exec_())

